services:
  mariadb:
    image: "mariadb:latest"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: Music2
      MARIADB_USER: root
      MARIADB_PASSWORD: 1234
    volumes:
      # persist data files into `datadir` volume managed by docker
      - datadir:/var/lib/mysql
      # bind-mount any sql files that should be run while initializing
      - ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    container_name: "mariadb_docker"
    build:  
      context: .
      dockerfile: "mariadb"
    networks:
      - "freezer_network"
    ports :
      - "3306:3306"
      
  proftpd:
    container_name: "proftpd_docker"
    build:
      context: .
      dockerfile: "proftpd"
    ports :
      - "21:21"
    networks:
      - "freezer_network"

  nginx:
    build:
      context: .
      dockerfile: "nginx" 
    container_name: "nginx_docker"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "mariadb"
    networks:  
       - "freezer_network"

networks:
  freezer_network:
    driver: "bridge"

volumes:
  datadir:
    external: true
