version: "3.7"

services:
  mariadb:
    container_name: "mariadb_docker"
    build:  
      context: .
      dockerfile: "mariadb"
    networks:
      freezer_network:
        ipv4_address: 149.50.0.4
    ports :
      - "3306:3306"
      
  proftpd:
    container_name: "proftpd_docker"
    build:
      context: .
      dockerfile: "proftpd"
    ports :
      - "21:21"
    networks:
      freezer_network:
        ipv4_address: 149.50.0.2

  nginx:
    build:
      context: .
      dockerfile: "nginx" 
    container_name: "nginx_docker"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "mariadb"
    networks:
      freezer_network:
        ipv4_address: 149.50.0.3


networks:
  freezer_network:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 149.50.0.0/16
          gateway: 149.50.0.1

